### PR TITLE
Upgrades Pynini version.

### LINKED ISSUE #6: Pynini 2.1.5 update
Pynini 2.1.5 was just released and we may want to update. It doesn't have any major API or performance changes so I think we can just edit the `environment.yml` and/or `requirements.txt` files.

### PR DESCRIPTION
**Pull request by kylebgorman**
Do not submit until CUNY-CL:latin_scansion PR 93# is merged and that
module is uploaded to PyPI though.

Closes #6.

### CODE REVIEW

**Comment by kylebgorman** [comment]
This should be ready now @jillianchang.

**Comment by jillianchang** [comment]
Did you get an email about the workflow error on the previous?

**Comment by kylebgorman** [comment]
Yes, it's related to Thrax though and the app only uses Thrax very indirectly (in that `all.far`, not changed on this PR, is built by it) so I would recommend we push on.

**Comment by jillianchang** [comment]
Okay, so it's ready to merge?

**Pull request merged**
